# Generated by Django 4.1.2 on 2022-10-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='channels_logo', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('telegram_link', models.URLField(null=True, verbose_name='Ссылка на телеграмм канал')),
                ('tgstat_link', models.URLField(null=True, verbose_name='Ссылка на тгстат')),
                ('telemetr_link', models.URLField(null=True, verbose_name='Ссылка на телеметр')),
                ('subscribes_count', models.IntegerField(default=0, verbose_name='Количество подписчиков')),
                ('coverage', models.IntegerField(null=True, verbose_name='Охваты')),
                ('ERR', models.IntegerField(null=True, verbose_name='ERR')),
                ('CPM', models.IntegerField(null=True, verbose_name='CPM')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
