# Generated by Django 4.1.2 on 2022-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Гео')),
                ('traffic_percentage', models.IntegerField(default=0, verbose_name='Трафик страны%')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife', models.IntegerField(default=0, verbose_name='Женский%')),
                ('man', models.IntegerField(default='0', verbose_name='Мужской%')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Описание отзыва')),
            ],
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='ERR',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='coverage',
        ),
        migrations.AddField(
            model_name='channel',
            name='RP',
            field=models.IntegerField(default=0, verbose_name='ERP индикатор'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='CPM',
            field=models.IntegerField(default=0, verbose_name='CPM индикатор'),
        ),
        migrations.AddField(
            model_name='channel',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='core.review', verbose_name='Отзывы'),
        ),
    ]
