# Generated by Django 4.1.2 on 2022-10-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_gender_review_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Канал'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Трафик стран', 'verbose_name_plural': 'Трафик стран'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='RP',
            new_name='ERP',
        ),
        migrations.AddField(
            model_name='channel',
            name='man',
            field=models.IntegerField(default='0', verbose_name='Мужской%'),
        ),
        migrations.AddField(
            model_name='channel',
            name='woman',
            field=models.IntegerField(default=0, verbose_name='Женский%'),
        ),
    ]
