# Generated by Django 4.1.2 on 2022-10-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_gender_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('title', 'cat_id')},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
    ]
