# Generated by Django 4.1.2 on 2022-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_channel_cat_id_alter_channel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='cat_id',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('title', 'category')},
        ),
    ]
