# Generated by Django 4.1.2 on 2022-10-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_channel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='traffic_percentage',
            field=models.IntegerField(default='%', verbose_name='Трафик страны%'),
        ),
        migrations.AddField(
            model_name='channel',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_channels', to='core.favorites'),
        ),
    ]
