# Generated by Django 4.1.2 on 2022-10-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorites_alter_country_traffic_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='core.favorites'),
        ),
    ]
