# Generated by Django 4.1.2 on 2022-10-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='title',
        ),
        migrations.AddField(
            model_name='favorites',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.users'),
            preserve_default=False,
        ),
    ]
