# Generated by Django 4.1.2 on 2022-10-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_channel_favorites_remove_favorites_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='ERP',
        ),
        migrations.AddField(
            model_name='channel',
            name='ERR',
            field=models.IntegerField(default=0, verbose_name='ERR индикатор'),
        ),
        migrations.AddField(
            model_name='channel',
            name='coverage',
            field=models.IntegerField(default=0, verbose_name='индикатор охвата'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='core.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=255, verbose_name='id пользователя'),
        ),
    ]
